// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5vEW6P4p8LQwWPTjPXdsTOl04NWvaAA',
    appId: '1:433338827717:android:393826e6519bb16d5481ac',
    messagingSenderId: '433338827717',
    projectId: 'auction-ai-app',
    storageBucket: 'auction-ai-app.firebasestorage.app',
  );

  // iOS 설정은 Firebase Console에서 iOS 앱을 추가한 후
  // GoogleService-Info.plist를 다운로드하여 아래 정보를 입력하세요
  // 또는 Firebase CLI를 사용하여 자동 생성: flutterfire configure
  // 현재는 Android만 지원하므로 임시로 Android 설정 재사용
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY5vEW6P4p8LQwWPTjPXdsTOl04NWvaAA',
    appId: '1:433338827717:ios:0000000000000000', // 임시 iOS 앱 ID
    messagingSenderId: '433338827717',
    projectId: 'auction-ai-app',
    storageBucket: 'auction-ai-app.firebasestorage.app',
    iosBundleId: 'com.auctionai.auction-ai-app',
  );
}
